"""Signal data structure for strategy output."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from decimal import Decimal
from typing import Optional

from txf.core.types import Side


@dataclass(frozen=True)
class Signal:
    """A trading signal generated by a strategy."""

    symbol: str
    side: Side
    strength: float = 1.0  # 0.0 to 1.0
    price: Optional[Decimal] = None
    reason: str = ""
    timestamp: Optional[datetime] = None
